/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 vk.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
*/
// *********************************************************************
// THIS FILE IS AUTO GENERATED!
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
// *********************************************************************
package com.vk.sdk.api

import com.google.gson.Gson
import com.google.gson.GsonBuilder

object GsonHolder {
    val gson: Gson by lazy { gsonBuilder.create() }

    val gsonBuilder: GsonBuilder by lazy { makeBuilder() }

    private fun makeBuilder(): GsonBuilder {
        val builder = GsonBuilder()
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetStatisticsStatsFields::class.java,
                com.vk.sdk.api.ads.dto.AdsGetStatisticsStatsFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetStatisticsPeriod::class.java,
                com.vk.sdk.api.ads.dto.AdsGetStatisticsPeriod.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsAdStatus::class.java,
                com.vk.sdk.api.ads.dto.AdsAdStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetUploadURLAdFormat::class.java,
                com.vk.sdk.api.ads.dto.AdsGetUploadURLAdFormat.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetCampaignsFields::class.java,
                com.vk.sdk.api.ads.dto.AdsGetCampaignsFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetDemographicsIdsType::class.java,
                com.vk.sdk.api.ads.dto.AdsGetDemographicsIdsType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsAdApproved::class.java,
                com.vk.sdk.api.ads.dto.AdsAdApproved.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsLookalikeRequest.SourceType::class.java,
                com.vk.sdk.api.ads.dto.AdsLookalikeRequest.SourceType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsLookalikeRequest.Status::class.java,
                com.vk.sdk.api.ads.dto.AdsLookalikeRequest.Status.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetSuggestionsLang::class.java,
                com.vk.sdk.api.ads.dto.AdsGetSuggestionsLang.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsCheckLinkLinkType::class.java,
                com.vk.sdk.api.ads.dto.AdsCheckLinkLinkType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetTargetingStatsAdFormat::class.java,
                com.vk.sdk.api.ads.dto.AdsGetTargetingStatsAdFormat.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsCriteriaSex::class.java,
                com.vk.sdk.api.ads.dto.AdsCriteriaSex.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsObjectType::class.java,
                com.vk.sdk.api.ads.dto.AdsObjectType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsTargSuggestionsSchoolsType::class.java,
                com.vk.sdk.api.ads.dto.AdsTargSuggestionsSchoolsType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsCampaignStatus::class.java,
                com.vk.sdk.api.ads.dto.AdsCampaignStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsStatsSexValue::class.java,
                com.vk.sdk.api.ads.dto.AdsStatsSexValue.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetPostsReachIdsType::class.java,
                com.vk.sdk.api.ads.dto.AdsGetPostsReachIdsType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetSuggestionsSection::class.java,
                com.vk.sdk.api.ads.dto.AdsGetSuggestionsSection.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsAccessRole::class.java,
                com.vk.sdk.api.ads.dto.AdsAccessRole.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsAccountType::class.java,
                com.vk.sdk.api.ads.dto.AdsAccountType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsAdCostType::class.java,
                com.vk.sdk.api.ads.dto.AdsAdCostType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetDemographicsPeriod::class.java,
                com.vk.sdk.api.ads.dto.AdsGetDemographicsPeriod.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsGetStatisticsIdsType::class.java,
                com.vk.sdk.api.ads.dto.AdsGetStatisticsIdsType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.ads.dto.AdsCampaignType::class.java,
                com.vk.sdk.api.ads.dto.AdsCampaignType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoSearchSort::class.java,
                com.vk.sdk.api.video.dto.VideoSearchSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoSearchFilters::class.java,
                com.vk.sdk.api.video.dto.VideoSearchFilters.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoEditAlbumPrivacy::class.java,
                com.vk.sdk.api.video.dto.VideoEditAlbumPrivacy.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoVideo.Type::class.java,
                com.vk.sdk.api.video.dto.VideoVideo.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoVideo.LiveStatus::class.java,
                com.vk.sdk.api.video.dto.VideoVideo.LiveStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoGetCommentsSort::class.java,
                com.vk.sdk.api.video.dto.VideoGetCommentsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoReportCommentReason::class.java,
                com.vk.sdk.api.video.dto.VideoReportCommentReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoRestrictionButton.Action::class.java,
                com.vk.sdk.api.video.dto.VideoRestrictionButton.Action.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoVideoFull.Type::class.java,
                com.vk.sdk.api.video.dto.VideoVideoFull.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoVideoFull.LiveStatus::class.java,
                com.vk.sdk.api.video.dto.VideoVideoFull.LiveStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoReportReason::class.java,
                com.vk.sdk.api.video.dto.VideoReportReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.video.dto.VideoAddAlbumPrivacy::class.java,
                com.vk.sdk.api.video.dto.VideoAddAlbumPrivacy.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallGetCommentsSort::class.java,
                com.vk.sdk.api.wall.dto.WallGetCommentsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallWallpostAttachmentType::class.java,
                com.vk.sdk.api.wall.dto.WallWallpostAttachmentType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallPostType::class.java,
                com.vk.sdk.api.wall.dto.WallPostType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallCommentAttachmentType::class.java,
                com.vk.sdk.api.wall.dto.WallCommentAttachmentType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallReportPostReason::class.java,
                com.vk.sdk.api.wall.dto.WallReportPostReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallGetFilter::class.java,
                com.vk.sdk.api.wall.dto.WallGetFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallPostSourceType::class.java,
                com.vk.sdk.api.wall.dto.WallPostSourceType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.wall.dto.WallReportCommentReason::class.java,
                com.vk.sdk.api.wall.dto.WallReportCommentReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesGetHistoryAttachmentsMediaType::class.java,
                com.vk.sdk.api.messages.dto.MessagesGetHistoryAttachmentsMediaType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesConversation.SpecialServiceType::class.java,
                com.vk.sdk.api.messages.dto.MessagesConversation.SpecialServiceType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesConversationPeerType::class.java,
                com.vk.sdk.api.messages.dto.MessagesConversationPeerType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesGetHistoryRev::class.java,
                com.vk.sdk.api.messages.dto.MessagesGetHistoryRev.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesKeyboardButton.Color::class.java,
                com.vk.sdk.api.messages.dto.MessagesKeyboardButton.Color.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesSendIntent::class.java,
                com.vk.sdk.api.messages.dto.MessagesSendIntent.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesTemplateActionTypeNames::class.java,
                com.vk.sdk.api.messages.dto.MessagesTemplateActionTypeNames.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.messages.dto.MessagesGetConversationsFilter::class.java,
                com.vk.sdk.api.messages.dto.MessagesGetConversationsFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.owner.dto.OwnerState.State::class.java,
                com.vk.sdk.api.owner.dto.OwnerState.State.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.board.dto.BoardDefaultOrder::class.java,
                com.vk.sdk.api.board.dto.BoardDefaultOrder.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.board.dto.BoardGetTopicsOrder::class.java,
                com.vk.sdk.api.board.dto.BoardGetTopicsOrder.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.board.dto.BoardGetTopicsPreview::class.java,
                com.vk.sdk.api.board.dto.BoardGetTopicsPreview.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.board.dto.BoardGetCommentsSort::class.java,
                com.vk.sdk.api.board.dto.BoardGetCommentsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.likes.dto.LikesType::class.java,
                com.vk.sdk.api.likes.dto.LikesType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.likes.dto.LikesGetListFilter::class.java,
                com.vk.sdk.api.likes.dto.LikesGetListFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.likes.dto.LikesGetListFriendsOnly::class.java,
                com.vk.sdk.api.likes.dto.LikesGetListFriendsOnly.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.auth.dto.AuthRestoreResponseDto.Success::class.java,
                com.vk.sdk.api.auth.dto.AuthRestoreResponseDto.Success.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.leads.dto.LeadsCheckedResult::class.java,
                com.vk.sdk.api.leads.dto.LeadsCheckedResult.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.leads.dto.LeadsGetUsersStatus::class.java,
                com.vk.sdk.api.leads.dto.LeadsGetUsersStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.appWidgets.dto.AppWidgetsGetAppImageUploadServerImageType::class.java,
                com.vk.sdk.api.appWidgets.dto.AppWidgetsGetAppImageUploadServerImageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.appWidgets.dto.AppWidgetsGetAppImagesImageType::class.java,
                com.vk.sdk.api.appWidgets.dto.AppWidgetsGetAppImagesImageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.appWidgets.dto.AppWidgetsGetGroupImagesImageType::class.java,
                com.vk.sdk.api.appWidgets.dto.AppWidgetsGetGroupImagesImageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.appWidgets.dto.AppWidgetsUpdateType::class.java,
                com.vk.sdk.api.appWidgets.dto.AppWidgetsUpdateType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.appWidgets.dto.AppWidgetsGetGroupImageUploadServerImageType::class.java,
                com.vk.sdk.api.appWidgets.dto.AppWidgetsGetGroupImageUploadServerImageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.fave.dto.FaveGetPagesType::class.java,
                com.vk.sdk.api.fave.dto.FaveGetPagesType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.fave.dto.FavePageType::class.java,
                com.vk.sdk.api.fave.dto.FavePageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.fave.dto.FaveAddTagPosition::class.java,
                com.vk.sdk.api.fave.dto.FaveAddTagPosition.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.fave.dto.FaveBookmarkType::class.java,
                com.vk.sdk.api.fave.dto.FaveBookmarkType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.fave.dto.FaveSetTagsItemType::class.java,
                com.vk.sdk.api.fave.dto.FaveSetTagsItemType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.fave.dto.FaveGetItemType::class.java,
                com.vk.sdk.api.fave.dto.FaveGetItemType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.polls.dto.PollsGetByIdNameCase::class.java,
                com.vk.sdk.api.polls.dto.PollsGetByIdNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.polls.dto.PollsBackground.Type::class.java,
                com.vk.sdk.api.polls.dto.PollsBackground.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.polls.dto.PollsCreateBackgroundId::class.java,
                com.vk.sdk.api.polls.dto.PollsCreateBackgroundId.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.polls.dto.PollsEditBackgroundId::class.java,
                com.vk.sdk.api.polls.dto.PollsEditBackgroundId.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.polls.dto.PollsGetVotersNameCase::class.java,
                com.vk.sdk.api.polls.dto.PollsGetVotersNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.utils.dto.UtilsDomainResolvedType::class.java,
                com.vk.sdk.api.utils.dto.UtilsDomainResolvedType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.utils.dto.UtilsGetLinkStatsInterval::class.java,
                com.vk.sdk.api.utils.dto.UtilsGetLinkStatsInterval.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.utils.dto.UtilsLinkCheckedStatus::class.java,
                com.vk.sdk.api.utils.dto.UtilsLinkCheckedStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.utils.dto.UtilsGetLinkStatsSource::class.java,
                com.vk.sdk.api.utils.dto.UtilsGetLinkStatsSource.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsOwnerXtrBanInfoType::class.java,
                com.vk.sdk.api.groups.dto.GroupsOwnerXtrBanInfoType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupSubject::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupSubject.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupXtrInvitedByAdminLevel::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupXtrInvitedByAdminLevel.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsRoleOptions::class.java,
                com.vk.sdk.api.groups.dto.GroupsRoleOptions.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupAdminLevel::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupAdminLevel.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupAccess::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupAccess.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsMarketState::class.java,
                com.vk.sdk.api.groups.dto.GroupsMarketState.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsBanInfoReason::class.java,
                com.vk.sdk.api.groups.dto.GroupsBanInfoReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupMarketCurrency::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupMarketCurrency.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupFullMemberStatus::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupFullMemberStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsMemberRoleStatus::class.java,
                com.vk.sdk.api.groups.dto.GroupsMemberRoleStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupPhotos::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupPhotos.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupVideo::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupVideo.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsSearchSort::class.java,
                com.vk.sdk.api.groups.dto.GroupsSearchSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupXtrInvitedByType::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupXtrInvitedByType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsSettingsTwitter.Status::class.java,
                com.vk.sdk.api.groups.dto.GroupsSettingsTwitter.Status.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsFilter::class.java,
                com.vk.sdk.api.groups.dto.GroupsFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupFullAgeLimits::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupFullAgeLimits.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupDocs::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupDocs.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupAudio::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupAudio.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupType::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGetMembersFilter::class.java,
                com.vk.sdk.api.groups.dto.GroupsGetMembersFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsAddressWorkInfoStatus::class.java,
                com.vk.sdk.api.groups.dto.GroupsAddressWorkInfoStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupWiki::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupWiki.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsTagAddTagColor::class.java,
                com.vk.sdk.api.groups.dto.GroupsTagAddTagColor.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsFields::class.java,
                com.vk.sdk.api.groups.dto.GroupsFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupFullMainSection::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupFullMainSection.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupIsClosed::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupIsClosed.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupFull.Wall::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupFull.Wall.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsCallbackServer.Status::class.java,
                com.vk.sdk.api.groups.dto.GroupsCallbackServer.Status.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsMemberRolePermission::class.java,
                com.vk.sdk.api.groups.dto.GroupsMemberRolePermission.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupRole::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupRole.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsCreateSubtype::class.java,
                com.vk.sdk.api.groups.dto.GroupsCreateSubtype.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsCreateType::class.java,
                com.vk.sdk.api.groups.dto.GroupsCreateType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsSearchType::class.java,
                com.vk.sdk.api.groups.dto.GroupsSearchType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupTopics::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupTopics.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsToggleMarketState::class.java,
                com.vk.sdk.api.groups.dto.GroupsToggleMarketState.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGetMembersSort::class.java,
                com.vk.sdk.api.groups.dto.GroupsGetMembersSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsAddAddressWorkInfoStatus::class.java,
                com.vk.sdk.api.groups.dto.GroupsAddAddressWorkInfoStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsTagBindAct::class.java,
                com.vk.sdk.api.groups.dto.GroupsTagBindAct.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupTag.Color::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupTag.Color.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsEditAddressWorkInfoStatus::class.java,
                com.vk.sdk.api.groups.dto.GroupsEditAddressWorkInfoStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsOnlineStatusType::class.java,
                com.vk.sdk.api.groups.dto.GroupsOnlineStatusType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupWall::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupWall.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsEditAgeLimits::class.java,
                com.vk.sdk.api.groups.dto.GroupsEditAgeLimits.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGetInvitedUsersNameCase::class.java,
                com.vk.sdk.api.groups.dto.GroupsGetInvitedUsersNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.groups.dto.GroupsGroupAgeLimits::class.java,
                com.vk.sdk.api.groups.dto.GroupsGroupAgeLimits.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.docs.dto.DocsGetType::class.java,
                com.vk.sdk.api.docs.dto.DocsGetType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.docs.dto.DocsGetMessagesUploadServerType::class.java,
                com.vk.sdk.api.docs.dto.DocsGetMessagesUploadServerType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.docs.dto.DocsDocAttachmentType::class.java,
                com.vk.sdk.api.docs.dto.DocsDocAttachmentType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.streaming.dto.StreamingGetStatsInterval::class.java,
                com.vk.sdk.api.streaming.dto.StreamingGetStatsInterval.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.streaming.dto.StreamingSetSettingsMonthlyTier::class.java,
                com.vk.sdk.api.streaming.dto.StreamingSetSettingsMonthlyTier.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.streaming.dto.StreamingGetStatsType::class.java,
                com.vk.sdk.api.streaming.dto.StreamingGetStatsType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.search.dto.SearchHintType::class.java,
                com.vk.sdk.api.search.dto.SearchHintType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesClickableSticker.Subtype::class.java,
                com.vk.sdk.api.stories.dto.StoriesClickableSticker.Subtype.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesClickableSticker.Style::class.java,
                com.vk.sdk.api.stories.dto.StoriesClickableSticker.Style.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesClickableSticker.Type::class.java,
                com.vk.sdk.api.stories.dto.StoriesClickableSticker.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesFeedItem.Type::class.java,
                com.vk.sdk.api.stories.dto.StoriesFeedItem.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesUploadLinkText::class.java,
                com.vk.sdk.api.stories.dto.StoriesUploadLinkText.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesStoryStatsState::class.java,
                com.vk.sdk.api.stories.dto.StoriesStoryStatsState.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stories.dto.StoriesStoryType::class.java,
                com.vk.sdk.api.stories.dto.StoriesStoryType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.notes.dto.NotesGetCommentsSort::class.java,
                com.vk.sdk.api.notes.dto.NotesGetCommentsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.notes.dto.NotesGetSort::class.java,
                com.vk.sdk.api.notes.dto.NotesGetSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.gifts.dto.GiftsGiftPrivacy::class.java,
                com.vk.sdk.api.gifts.dto.GiftsGiftPrivacy.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.addresses.dto.AddressesFields::class.java,
                com.vk.sdk.api.addresses.dto.AddressesFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersUserType::class.java,
                com.vk.sdk.api.users.dto.UsersUserType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersSearchSex::class.java,
                com.vk.sdk.api.users.dto.UsersSearchSex.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersOnlineInfo.Status::class.java,
                com.vk.sdk.api.users.dto.UsersOnlineInfo.Status.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersSearchSort::class.java,
                com.vk.sdk.api.users.dto.UsersSearchSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersUserRelation::class.java,
                com.vk.sdk.api.users.dto.UsersUserRelation.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersRelative.Type::class.java,
                com.vk.sdk.api.users.dto.UsersRelative.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersGetNameCase::class.java,
                com.vk.sdk.api.users.dto.UsersGetNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersGetFollowersNameCase::class.java,
                com.vk.sdk.api.users.dto.UsersGetFollowersNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersReportType::class.java,
                com.vk.sdk.api.users.dto.UsersReportType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersFields::class.java,
                com.vk.sdk.api.users.dto.UsersFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.users.dto.UsersSearchStatus::class.java,
                com.vk.sdk.api.users.dto.UsersSearchStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketSearchSort::class.java,
                com.vk.sdk.api.market.dto.MarketSearchSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketSearchRev::class.java,
                com.vk.sdk.api.market.dto.MarketSearchRev.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketMarketItemAvailability::class.java,
                com.vk.sdk.api.market.dto.MarketMarketItemAvailability.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketSearchStatus::class.java,
                com.vk.sdk.api.market.dto.MarketSearchStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketGetCommentsSort::class.java,
                com.vk.sdk.api.market.dto.MarketGetCommentsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketReportCommentReason::class.java,
                com.vk.sdk.api.market.dto.MarketReportCommentReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.market.dto.MarketReportReason::class.java,
                com.vk.sdk.api.market.dto.MarketReportReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.callback.dto.CallbackGroupOfficerRole::class.java,
                com.vk.sdk.api.callback.dto.CallbackGroupOfficerRole.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.callback.dto.CallbackMessageType::class.java,
                com.vk.sdk.api.callback.dto.CallbackMessageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.callback.dto.CallbackLikeAddRemove.ObjectType::class.java,
                com.vk.sdk.api.callback.dto.CallbackLikeAddRemove.ObjectType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.callback.dto.CallbackGroupMarket::class.java,
                com.vk.sdk.api.callback.dto.CallbackGroupMarket.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.callback.dto.CallbackGroupJoinType::class.java,
                com.vk.sdk.api.callback.dto.CallbackGroupJoinType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsSearchNameCase::class.java,
                com.vk.sdk.api.friends.dto.FriendsSearchNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsGetSuggestionsNameCase::class.java,
                com.vk.sdk.api.friends.dto.FriendsGetSuggestionsNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsGetRequestsSort::class.java,
                com.vk.sdk.api.friends.dto.FriendsGetRequestsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsGetOrder::class.java,
                com.vk.sdk.api.friends.dto.FriendsGetOrder.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsGetNameCase::class.java,
                com.vk.sdk.api.friends.dto.FriendsGetNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsGetSuggestionsFilter::class.java,
                com.vk.sdk.api.friends.dto.FriendsGetSuggestionsFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsAddResponseDto::class.java,
                com.vk.sdk.api.friends.dto.FriendsAddResponseDto.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.FriendDeleted::class.java,
                com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.FriendDeleted.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.InRequestDeleted::class.java,
                com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.InRequestDeleted.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.SuggestionDeleted::class.java,
                com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.SuggestionDeleted.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.OutRequestDeleted::class.java,
                com.vk.sdk.api.friends.dto.FriendsDeleteResponseDto.OutRequestDeleted.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.friends.dto.FriendsFriendStatusStatus::class.java,
                com.vk.sdk.api.friends.dto.FriendsFriendStatusStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.orders.dto.OrdersChangeStateAction::class.java,
                com.vk.sdk.api.orders.dto.OrdersChangeStateAction.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountGetInfoFields::class.java,
                com.vk.sdk.api.account.dto.AccountGetInfoFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountPushParamsMode::class.java,
                com.vk.sdk.api.account.dto.AccountPushParamsMode.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountSaveProfileInfoSex::class.java,
                com.vk.sdk.api.account.dto.AccountSaveProfileInfoSex.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountSaveProfileInfoRelation::class.java,
                com.vk.sdk.api.account.dto.AccountSaveProfileInfoRelation.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountSaveProfileInfoBdateVisibility::class.java,
                com.vk.sdk.api.account.dto.AccountSaveProfileInfoBdateVisibility.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountNameRequestStatus::class.java,
                com.vk.sdk.api.account.dto.AccountNameRequestStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountOffer.LinkType::class.java,
                com.vk.sdk.api.account.dto.AccountOffer.LinkType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountPushParamsSettings::class.java,
                com.vk.sdk.api.account.dto.AccountPushParamsSettings.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountPushParamsOnoff::class.java,
                com.vk.sdk.api.account.dto.AccountPushParamsOnoff.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.account.dto.AccountGetCountersFilter::class.java,
                com.vk.sdk.api.account.dto.AccountGetCountersFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosReportReason::class.java,
                com.vk.sdk.api.photos.dto.PhotosReportReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosPhotoSizesType::class.java,
                com.vk.sdk.api.photos.dto.PhotosPhotoSizesType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosGetCommentsSort::class.java,
                com.vk.sdk.api.photos.dto.PhotosGetCommentsSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosTagsSuggestionItemButton.Action::class.java,
                com.vk.sdk.api.photos.dto.PhotosTagsSuggestionItemButton.Action.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosTagsSuggestionItemButton.Style::class.java,
                com.vk.sdk.api.photos.dto.PhotosTagsSuggestionItemButton.Style.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosReportCommentReason::class.java,
                com.vk.sdk.api.photos.dto.PhotosReportCommentReason.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.photos.dto.PhotosImageType::class.java,
                com.vk.sdk.api.photos.dto.PhotosImageType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.pages.dto.PagesPrivacySettings::class.java,
                com.vk.sdk.api.pages.dto.PagesPrivacySettings.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.pages.dto.PagesSaveAccessView::class.java,
                com.vk.sdk.api.pages.dto.PagesSaveAccessView.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.pages.dto.PagesSaveAccessEdit::class.java,
                com.vk.sdk.api.pages.dto.PagesSaveAccessEdit.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetNameCase::class.java,
                com.vk.sdk.api.apps.dto.AppsGetNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsSendRequestType::class.java,
                com.vk.sdk.api.apps.dto.AppsSendRequestType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetLeaderboardType::class.java,
                com.vk.sdk.api.apps.dto.AppsGetLeaderboardType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsAppLeaderboardType::class.java,
                com.vk.sdk.api.apps.dto.AppsAppLeaderboardType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsScope.Name::class.java,
                com.vk.sdk.api.apps.dto.AppsScope.Name.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetFriendsListType::class.java,
                com.vk.sdk.api.apps.dto.AppsGetFriendsListType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetScopesType::class.java,
                com.vk.sdk.api.apps.dto.AppsGetScopesType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetCatalogSort::class.java,
                com.vk.sdk.api.apps.dto.AppsGetCatalogSort.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetPlatform::class.java,
                com.vk.sdk.api.apps.dto.AppsGetPlatform.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.apps.dto.AppsGetCatalogFilter::class.java,
                com.vk.sdk.api.apps.dto.AppsGetCatalogFilter.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.notifications.dto.NotificationsSendMessageError.Code::class.java,
                com.vk.sdk.api.notifications.dto.NotificationsSendMessageError.Code.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.notifications.dto.NotificationsGetFilters::class.java,
                com.vk.sdk.api.notifications.dto.NotificationsGetFilters.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.notifications.dto.NotificationsNotificationParent.Type::class.java,
                com.vk.sdk.api.notifications.dto.NotificationsNotificationParent.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.notifications.dto.NotificationsNotificationParent.LiveStatus::class.java,
                com.vk.sdk.api.notifications.dto.NotificationsNotificationParent.LiveStatus.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseOkResponseDto::class.java,
                com.vk.sdk.api.base.dto.BaseOkResponseDto.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseUserGroupFields::class.java,
                com.vk.sdk.api.base.dto.BaseUserGroupFields.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseLinkButtonStyle::class.java,
                com.vk.sdk.api.base.dto.BaseLinkButtonStyle.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseSex::class.java,
                com.vk.sdk.api.base.dto.BaseSex.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BasePropertyExists::class.java,
                com.vk.sdk.api.base.dto.BasePropertyExists.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseStickerAnimation.Type::class.java,
                com.vk.sdk.api.base.dto.BaseStickerAnimation.Type.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseBoolInt::class.java,
                com.vk.sdk.api.base.dto.BaseBoolInt.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseLinkButtonActionType::class.java,
                com.vk.sdk.api.base.dto.BaseLinkButtonActionType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.base.dto.BaseLinkProductStatus.Value::class.java,
                com.vk.sdk.api.base.dto.BaseLinkProductStatus.Value.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.stats.dto.StatsGetInterval::class.java,
                com.vk.sdk.api.stats.dto.StatsGetInterval.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.widgets.dto.WidgetsCommentMediaType::class.java,
                com.vk.sdk.api.widgets.dto.WidgetsCommentMediaType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedItemWallpostFeedbackType::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedItemWallpostFeedbackType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedItemDigest.Template::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedItemDigest.Template.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedNewsfeedItemType::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedNewsfeedItemType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedItemWallpostType::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedItemWallpostType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedUnsubscribeType::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedUnsubscribeType.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedFilters::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedFilters.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedGetBannedNameCase::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedGetBannedNameCase.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedCommentsFilters::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedCommentsFilters.Serializer())
        builder.registerTypeAdapter(com.vk.sdk.api.newsfeed.dto.NewsfeedIgnoreItemType::class.java,
                com.vk.sdk.api.newsfeed.dto.NewsfeedIgnoreItemType.Serializer())
        return builder
    }
}
